<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // 에러가 터졌을때의 try_catch문
        try {
            console.log('AAAA'); // 실행됨
            const result = new Array(-1);
            console.log('BBBB'); // 예외발생 후 이므로 실행 안됨
        } catch (e) {
            console.error('catch : ' + e.name); // 실행됨!!
        }

        console.log('(1) try_catch 끝');

        console.log('--------------------');

        // 에러가 안터졌을때의 try_catch문

        try {
            console.log('AAAA');
            console.log('BBBB');
            console.log('CCCC');
        } catch(e) {
            console.error(e.name); // 실행 안 됨!! (e.name : 에러 이름 찍어본 것)
        }

        console.log('(2) try_catch 끝');

        console.log('--------------------');

        try {
            console.log('AAAA');
            const result = new Array(-1);
            console.log('BBBB');
        } catch (e) {
            console.error('catch : ' + e.name);
        } finally {
            console.log('무조건 실행 됨!');
        }

        console.log('(3) try_catch 끝');

        console.log('--------------------');

    </script>
</body>

</html>


<!--
- 예외처리 해주는것이 try_catch문
예외가 발생될 가능성이 높은 부분 try로 감싸준다
(사실 모든 소스 try catch문으로 감싸도 됨)

catch : 에러가 터졌을때만(예외가 발생됐을때만) 실행됨

finally : 예외가 발생 됐든 안됐든 무조건 실행되는 부분

-->